version: '3'
services:
  postgres-db:
    image: postgres:16-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env_vars.env
