# Generated by Django 3.2.21 on 2024-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_alter_attachment_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution'), ('PA', 'Partially Approved')], default='PS', max_length=50),
        ),
    ]
