# Generated by Django 4.1.1 on 2024-11-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_alter_attachment_adm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='funded_investments',
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution'), ('PA', 'Partially Approved')], default='PS', max_length=50),
        ),
        migrations.CreateModel(
            name='PackageFundedInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.package')),
            ],
            options={
                'db_table': 'investments_package_funded_investments',
            },
        ),
    ]
