# Generated by Django 4.1.1 on 2024-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0019_remove_package_funded_investments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='funded_investments',
            field=models.ManyToManyField(related_name='packages', through='investments.PackageFundedInvestment', to='investments.investment'),
        ),
    ]
