# Generated by Django 3.2.25 on 2024-11-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_auto_20241110_1306'),
    ]

    operations = [
        migrations.RunSQL("UPDATE investments_package_funded_investments "
                          "SET "
                          "status = (CASE WHEN ip.status in ('A', 'R') THEN ip.status ELSE 'P' END), "
                          "rejection_reason = ip.rejection_reason "
                          "FROM main.investments_package_funded_investments fip "
                          "INNER JOIN main.investments_package ip "
                          "WHERE ip.id = fip.package_id"),
    ]
