# Generated by Django 4.1.1 on 2024-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_package_funded_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='imported_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
