# Generated by Django 4.1.1 on 2024-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0021_investment_imported_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='real_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
